name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    name: English Strings Static Validations
    runs-on: zendesk-stable
    env:
      BUNDLE_ZDREPO__JFROG__IO: "${{ secrets.BUNDLE_ZDREPO__JFROG__IO }}"
    steps:
    - uses: zendesk/checkout@v4
    - name: Set up Ruby
      uses: zendesk/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - run: bundle init # may be required for projects with no other Ruby-related config
    - run: gem install zendesk_i18n_dev_tools --source https://$BUNDLE_ZDREPO__JFROG__IO@zdrepo.jfrog.io/zdrepo/api/gems/gems-local/
    - run: validate_string_sweep_files 'translations.yml'
